import java.util.HashMap;
import java.util.Map;


rule "StartProcessNow"

    ruleflow-group "startNow"
	no-loop true
	lock-on-active true

    when
        $op : Operacao( )
    then
        System.out.println("INICIANDO PROCESSO PARA TESTE UNITARIO 1");
        Map params = new HashMap();
        params.put("o1", $op);

        System.out.println("... iniciando processo...");
        kcontext.getKnowledgeRuntime().startProcess("tesouraria.Fluxo", params);

        System.out.println("... disparando regras...");
        kcontext.getKnowledgeRuntime().fireAllRules2222();
        //retract($op);
        
end