import java.util.HashMap;
import java.util.Map;


rule "StartProcess"

    ruleflow-group "start"
	no-loop true
	lock-on-active true

    when
        $op : Operacao( )
    then
        System.out.println("INICIANDO PROCESSO PARA TESTE UNITARIO");
        Map params = new HashMap();
        params.put("o1", $op);

        System.out.println("... iniciando processo...");
        kcontext.getKnowledgeRuntime().startProcess("tesouraria.Fluxo", params);

        System.out.println("... disparando regras...");
        kcontext.getKnowledgeRuntime().fireAllRules();
        //retract($op);
        
end