package com.redhat.tesouraria;



import java.util.HashMap;
import java.util.Map;


rule "StartProcess"

    ruleflow-group "start"
	no-loop true
	lock-on-active true

    when
        $op : Operacao( )
    then
        System.out.println("INICIANDO PROCESSO PARA TESTE UNITARIO 1");
        Map params = new HashMap();
        params.put("o1", $op);

        System.out.println("... iniciando processo...");

        
        //create the instance, but don't start it yet
        org.kie.api.runtime.process.ProcessInstance processInstance = kcontext.getKnowledgeRuntime().createProcessInstance("tesouraria.Fluxo", params);

        //insert the instance in the WM: this will create the activation of the other rule
        insert(processInstance);

        //now, start the process
        kcontext.getKnowledgeRuntime().startProcessInstance(processInstance.getId());        
        retract($op);
        retract(processInstance);

        
        
end