package com.redhat.tesouraria;



import java.util.HashMap;
import java.util.Map;


rule "StartProcess"

    ruleflow-group "start"
	no-loop true
	lock-on-active true

    when
        $w : Wrapper( )
    then
        System.out.println("INICIANDO PROCESSO PARA TESTE UNITARIO 1");
        Map params = new HashMap();
        params.put("o1", $w.getOperacao());

        System.out.println("... iniciando processo...");

        System.out.println("... 1 ...");

        //create the instance, but don't start it yet
        org.kie.api.runtime.process.ProcessInstance processInstance = kcontext.getKnowledgeRuntime().createProcessInstance("tesouraria.Fluxo", params);

        System.out.println("... 2 ...");

        //insert the instance in the WM: this will create the activation of the other rule
        //insertLogical(processInstance);

        System.out.println("... 3 ...");

        //now, start the process
        kcontext.getKnowledgeRuntime().startProcessInstance(processInstance.getId());        
        
        System.out.println("... 4 ...");
        
        retract($w);
        retract(processInstance);

        
        
end