package com.redhat.tesouraria;

import java.util.HashMap;
import java.util.Map;
import org.drools.runtime.process.ProcessInstance;

rule "StartProcess"

    ruleflow-group "start"

    when
        $op : Operacao( )
    then
        System.out.println("INICIANDO PROCESSO PARA TESTE UNITARIO");
        Map params = new HashMap();
        params.put("operacao", op);
        ProcessInstance pi = kcontext.getKnowledgeRuntime().startProcess("tesouraria.Fluxo", params);
        
end