package com.redhat.tesouraria;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Operacao implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Operacao() {
    }

}